version: "3.7"
services:
  product-app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URI=mongodb://mongo:27017
  mongo:
    # container_name: mongodb
    image: mongo:latest
    #ports:
    # - 27017:27017